# Étape 1 : Build de l'application React
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Étape 2 : Serveur Nginx pour servir les fichiers statiques
FROM nginx:alpine
# Copie le build de React dans le dossier par défaut de Nginx
COPY --from=build /app/dist /usr/share/nginx/html
# Copie ta config nginx
COPY nginx-prod.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]